### ISSUE TITLE
Use of tilePatIdx

### ISSUE THREAD

**Issue by gatecat** [SymbiFlow/fpga-interchange-schema#17]
I can't find a use or purpose for the `tilePatIdx` field, it seems like it might be intended for some future graph folding work but if it's not currently being used then that should be made clear.

**Comment by litghost** [comment]
I actually think it might be something we should just remove (for now).  It's a property from RapidWright/Vivado, but it is undocumented.

**Comment by clavin-xlnx** [comment]
Sure, from the RapidWright/Vivado perspective, its ok to remove.  Since the device models don't need to be rebuilt in RapidWright from the Interchange, this won't be a problem.
